name: x86_64

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
  pull_request:

jobs:
  x86_64:
    name: "mingw-w64-x86_64 All"
    runs-on: [self-hosted, windows, x64]
    timeout-minutes: 960
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Cache msys64
        id: cache-msys64
        uses: 1480c1/cache@mabs
        with:
          path: msys64/home/CCOM-9020M$/.ccache
          key: ${{ runner.os }}-msys64

      - name: Get ini file
        shell: pwsh
        run: Invoke-WebRequest https://pastebin.com/raw/07hLkLza -OutFile build/media-autobuild_suite.ini

      - name: Replace do_prompt
        shell: pwsh
        run: sed -i 's/do_prompt /echo /g' build/media-suite_helper.sh build/media-suite_compile.sh

      - name: Compile the suite
        shell: cmd
        run: media-autobuild_suite.bat
      #- uses: actions/upload-artifact@v1 # Only on distributable builds
      #  with:
      #    name: mabs-x84_64
      #    path: local64
